import { Metadata } from "next";
import { ModalProvider } from "@/src/app/providers/ModalProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ModalProvider>
        <body>{children}</body>
      </ModalProvider>
    </html>
  );
}
